name: Periodic database builder

on:
  schedule:
    # Update the database every sunday
    # Better not do it to often to avoid problems with exploitdb
    - cron:  '0 0 * * 0'
  push:
    branches:
      - workflow


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests pandas
        sudo apt install fd-find ripgrep
    - name: Cache cve sources
      uses: actions/cache@v3
      with:
        key: cve-skiplist-and-database
        path: |
          ~/.cache/cve_exploit_mapper
          cve_exploit_mapping.csv
    - name: Build the database
      run: |
        export XDG_CACHE_HOME=$HOME/.cache
        mkdir -p $XDG_CACHE_HOME/cve_exploit_mapper
        cp exploitdb-skip.csv $XDG_CACHE_HOME/cve_exploit_mapper/
        if [ -f all.csv ]; then
            python3 cve_exploit_mapper -v --infile all.csv --outfile cve_exploit_mapping.csv --scraper metasploit,trickest,exploitdb
        else
            python3 cve_exploit_mapper -v --outfile cve_exploit_mapping.csv --scraper metasploit,trickest,exploitdb
        fi
    - name: Upload the database
      uses: actions/upload-artifact@v3
      with:
        name: cve_exploit_mapping
        path: cve_exploit_mapping.csv
